### ISSUE TITLE
Plugin is not supported in Intelij 2021.1

### ISSUE THREAD

**Issue by jimmymain** [mplushnikov/lombok-intellij-plugin#1028]
### Expected behavior
The plugin can be loaded by Intelij 2021.1

### Version information

 * **IDEA Version: 2021.1**
 * **JDK Version:1.8.0_281**
 * **OS Type & Version:Windows 10** 
 * **Lombok Plugin Version:0.34.1**_

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_
 1. Attempt to install the plugin
 2. Plugin Lombok version 0.34.1 is not compatible with the current version of the IDE

## Is there a hack that can resolve this in the meantime?

**Comment by EnjoyB** [comment]
Maybe, I'm not representative of this community, but
**From Readme.md:**

> 💥 Breaking News: Starting with IntelliJ version 2020.3 lombok plugin will be integrated and included in IntelliJ by default!. 💥

I have just now upgraded intellij to newest version (i.e. 2021.1) and Lombok is bundled(Therefore, it is not needed to install manually) in newest version and everything is working very smoothly right now. 

Please try it again, if not working, escalate it again.

**Comment by jimmymain** [comment]
I am closing this issue, it is now bundled

**Comment by DilipDalwadi** [comment]
> ### The plugin cannot be loaded into Intelij 2021.1, even when installed from disk.
> ### Expected behavior
> 
> The plugin can be loaded by Intelij 2021.1
> ### Version information
> 
>     * **IDEA Version: 2021.1**
> 
>     * **JDK Version:1.8.0_281**
> 
>     * **OS Type & Version:Windows 10**
> 
>     * **Lombok Plugin Version:0.34.1**_
> 
> 
> ### Steps to reproduce
> 
> _What steps do we need to take to reproduce this issue?_
> 
>     1. Attempt to install the plugin
> 
>     2. Plugin Lombok version 0.34.1 is not compatible with the current version of the IDE
> 
> 
> ## Is there a hack that can resolve this in the meantime?

I also got the save incompatibility version error message. 
`Plugin 'Lombok' (version '0.34.1-2021.1') is not compatible with the current version of the IDE, because it requires build 191.* or older but the current build is IE-212.5284.55`

I changed the version in plugin.xml file of META-INF directory of lombok-plugin-0.34.1-2019.1.jar file and It works for me. These are the steps which I did to change the idea version.

1. Download idea plugin jar file from Jetbrains website: https://plugins.jetbrains.com/plugin/6317-lombok/versions/stable/108259
2. Extract ZIP file
3. Go to lib directory lombok-plugin-0.34.1-2019.1 > lombok-plugin > lib
4. Copy or download META-INF > plugin.xml file from lombok-plugin-0.34.1-2019.1.jar file. Create META-INF directory inside lib directory and paste plugin.xml in META-INF directory.
5. Search idea version '191.*' and replace your IntelliJ IDE version. For example, I have installed Intellij IE-212.5284.55. So replaced the line as below 
`<idea-version since-build="191.6183" until-build="IE-212.*"/>`
6. Save it and replace plugin.xml file in lombok-plugin-0.34.1-2019.1.jar using below command.
`jar uf lombok-plugin-0.34.1-2019.1.jar META-INF/plugin.xml`
7. Go to IntelliJ plugins and install this plugin.

I have attached my META-INF directory of Lombok plugin for reference.
[META-INF.zip](https://github.com/mplushnikov/lombok-intellij-plugin/files/7299286/META-INF.zip)

**Comment by XilinJia** [comment]
Further from  [@DilipDalwadi (https://github.com/mplushnikov/lombok-intellij-plugin/issues/1028#issuecomment-937485680) I downloaded lombok-plugin-0.34-2020.2.zip from marketplace, unzip it, went to the META-INF directory, changed in the xml file the line to <idea-version since-build="191.6183" until-build="IE-212.*"/>, then saved the zip, installed the plugin from disk on Android Studio.  Things seem to work - previous errors regarding unresolved getter functions now gone.  Pretty brute force.  Not sure if there will be side effects, but who knows if this plugin will be updated after next year?
