### ISSUE TITLE
Support @Slf4j with custom logger name

### ISSUE THREAD

**Issue by php-coder** [mplushnikov/lombok-intellij-plugin#128]
Hello,

thank you for your plugin, it's working well except only one thing: I'm using `@Slf4j` and have `src/lombok.config` with the folioing content:

```
config.stopBubbling = true
lombok.addGeneratedAnnotation = false
lombok.anyConstructor.suppressConstructorProperties = true
lombok.log.fieldName = LOG
```

With this configuration IDEA highlights LOG variable and says "Cannot resolve symbol".

**Comment by AlexejK** [comment]
I believe this is basically due to Issue #53 . Because if you move lombok.config to src/main/java it works just fine. I'm using LOG variable in all of my projects.

There has been an issue at some point where LOG variable couldnt be resolved, but doing reload of project helped. But your issue I think is due to incorrect locaiton of lombok.config file.

Ideally Issue #53 should be fixed and this would resolve your problem too, but for now we simply have to place the config file in the default package.

**Comment by mplushnikov** [comment]
New version (0.11) of plugin was released today. It contains many improvements for configuration system of lombok. This issue should be fixed now.
