### ISSUE TITLE
@Builder supports setter for final field (@Value)

### ISSUE THREAD

**Issue by punkratz312** [mplushnikov/lombok-intellij-plugin#202]
The field **age** gets initialized with 0. As the @Value annotation makes the field final the implizit @AllArgsConstructor [https://projectlombok.org/features/Value.html] does not provide the field but the builder does.

Maybe it would be an solution orientate at the params the constructor provides.

PS: I would like to be able to pre initialize the field **age** and be at the same time able to override it by the builder if needed, but that would be an lombok issue.

![screen shot 2016-04-08 at 13 16 36](https://cloud.githubusercontent.com/assets/8830888/14382180/2fd82098-fd8c-11e5-8008-a261291e0c76.png)

Example:

@Value
@Builder
public class ValueExample {

    String name;
    int age = 0;
    double score;

    public void la() {

        ValueExample.builder().age(1).build();
    }

}

![screen shot 2016-04-08 at 13 21 30](https://cloud.githubusercontent.com/assets/8830888/14382276/d294025c-fd8c-11e5-954a-3425b05aacc8.png)

**Comment by AlexejK** [comment]
Your example has errors even in Eclipse with lombok installed. I believe this is because of conflics between `@Builder` and `@Value`.

Can you provide a working example of the code in Eclipse for this issue that fails in IntelliJ?
Otherwise I would suggest you refer back to original lombok project and file a bug there:  https://github.com/rzwitserloot/lombok

**Comment by Janmm14** [comment]
Intellij currently does not have a proper API for setting the final keyword, see #56

**Comment by punkratz312** [comment]
Thanks for the help 👍
