### ISSUE TITLE
@Setter(AccessLevel.NONE) triggers "final field is not allowed"

### ISSUE THREAD

**Issue by eekboom** [mplushnikov/lombok-intellij-plugin#226]
We sometimes use @Setter on class level, but @Setter(AccessLevel.NONE) to suppress the setter for individual fields.

The plugin's annotations inspection still complains that 
@lombok.Setter on final field is not allowed
for 

```
@Setter(AccessLevel.NONE)
private final String bug = "final";
```

**Comment by Janmm14** [comment]
If you use Setter on class level it ignores final fields.

**Comment by mplushnikov** [comment]
@Setter on final field is useless, because lombok ignores all final fields
(and fields that start with $ or are static). So you can simple remove you field annotation:)

But you are right, it's working some different than lombok self at the moment.

Annotation inspection should only warn you, because you will get only a warning by lombok compiler: "Not generating setter for this field: Setters cannot be generated for final fields." later in this case.
And it is a warning only for all other AccessLevels but not for AccessLevel.NONE, like in your example.

I will chnage it, to be more compatible with lombok implementation.
