### ISSUE TITLE
Setter generation fails on class implementing interface

### ISSUE THREAD

**Issue by mmoehring** [mplushnikov/lombok-intellij-plugin#237]
System: InelliJ 2016.1.2, Java 8, OS X 10.10

When trying to generate generate a setter for class which implements an interface where the setter is part of the interface, it fails. Minimal example:

```java
public interface Test {
    void foo(boolean foo);
}
```
```java
@Accessors(fluent = true)
public final class TestImpl implements Test {
    @Setter private boolean foo;
}
```

It triggers the following errors in IntelliJ:
> Error:(10, 14) java: de.foo.bar.TestImpl is not abstract and does not override abstract method foo(boolean) in de.foo.bar.Test

> Error:(11, 13) java: foo(boolean) in de.foo.bar.TestImpl cannot implement foo(boolean) in de.foo.bar.Test
  return type de.foo.bar.TestImpl is not compatible with void

When using DeLombok on the setter it generates the following code:
```java
public TestImpl foo(final boolean foo) {
    this.foo = foo;
    return this;
}
```

**Comment by AlexejK** [comment]
Does this work for you in Eclipse?

Because from what I see you are requesting a fluent accessor setup which means a setter will return the instance of the class (read `return this`). This is not compatible with your interface definition that wants a `void` method with exactly same parameters.

Please refer to Lombok Documentation for Accessor: https://projectlombok.org/features/experimental/Accessors.html

**Comment by mmoehring** [comment]
My bad... I overlooked that chain defaults to true for setters!
Setting it to false resolves the problem.

**Comment by AlexejK** [comment]
Nice we sorted it out quickly :)
