### ISSUE TITLE
Inspection that suggest to convert an explicit declaration into using val

### ISSUE THREAD

**Issue by twilek** [mplushnikov/lombok-intellij-plugin#239]
This is not an issue but a feature request. val declarations works great with the plugin nowadays. One thing I miss though is a code inspection that suggest to turn an explicit declaration into a val declaration.

In  other words, an inspection that ask to do this:
`MyObject myObject = new MyObject();` ---> `val myObject = new MyObject();`

**Comment by AlexejK** [comment]
I think we need to be a bit careful about this feature.
This inspection should only work to remove verbosity and not cause more confusion.

My __personal__ view of `val` usage is:
It should only be used on either streams or cases where the same type information is repeated multiple times (like the example in the original issue). 
Places where `val` might cause more harm is when you have something like `val foo = myObj.doSomething();` In this case you have no idea when reading the code what `myObj.doSomething()` returns and this becomes counterproductive when it comes to readability of the code.

This type of inspection, if added, should be very smart or it may be more annoying than anything.

**Comment by twilek** [comment]
The best thing is to make it possible for the user to enable or disable the inspection. In that way everyone can choose if it suits them or not.

I do not think this is really the right forum for personal discussions about the "be or not to be" of val, but if you want my opinion you can read it here http://stackoverflow.com/questions/3443858/c-sharp-var-keyword-equivalent-in-java#comment14964521_3443863 (TL;TR I think val shall be used everywhere where it can be used, because it "forces" a developer to write more clean code, since the code gets pretty much unreadable if you use poor names like `foo`)

**Comment by AlexejK** [comment]
I can agree that it's not for a personal opinion, however I am cautious about adding something that may lead to some future anti-patterns (which it may become, depending on where you are working).

I think the "forcing to make it readable" is not true for most less experienced (or just more sloppy) devs. For it to truly work there has to be a 100% buy-in from all team members and also something in place (at least like reviews) that cover this piece. My concern with `val` "everywhere" is probably the fact that I tend to think about "what will be most maintainable for the team in the long run" instead of "whats the most maintainable for me". Those are "slightly" different.

But, I'm not going to start a battle about to use or not use val in all cases, just like there is no point of doing "emacs vs vi" :)

The point is, we need to consider it all, and possibly the best way forward would be to make this inspection disabled by default and maybe configurable to some extend to allow for granularity or logical checking of some things

**Comment by twilek** [comment]
I'm working in a team too, and have worked in very many teams over the years, both small and large , where val/var with great success without any problems, so I'm not walking about what is most maintainable for _me_, but for _the team_. As I said, val makes you think twice before naming a variable so _other_ developers more easily can understand the code. In my opinion less experienced or sloppy programmers shall be promoted to write better code, not be promoted to keep on writing sloppy code, that is almost always best for the whole team, and there val can help you. If you disagree it is fine, what I am aware of no IDEA Inspection is forced, so if it doesn't fit you or your team , you shall of course be able to disable it.

**Comment by AlexejK** [comment]
Well, question is not if it should be added or not :) It's a good addition.

The things to iron out is about the granularity/configuration of the inspection as well as if it should be enabled or disabled by default.

It may sound like a small thing, but it still is important IMO :)

**Comment by twilek** [comment]
The only thing I asked for was a code inspection that suggest to turn an explicit declaration into a val declaration. I really do not care if it is disabled by default, that would be fine for me. I really miss this feature for the reason that it is make it easier to make it clear that everyone in the team shall use val.

**Comment by mplushnikov** [comment]
Is handled by #718 (PR #754)
