### ISSUE TITLE
'Lombok Depenency is possible outdated' message appears now by default

### ISSUE THREAD

**Issue by zkiss** [mplushnikov/lombok-intellij-plugin#267]
Since I've upgraded to version 0.12.16 of the plugin, I keep getting several outdated lombok dependency messages every time I start intellij: https://i.imgsafe.org/875151bd8c.png

- Should not produce several instances of the same message
- I have found no way to turn it off. The setting in Settings/Other Settings/Lombok plugin/Enable lombok version warning is turned off (unchecked) and I'm still getting the messages.

Quite annoying.

**Comment by AlexejK** [comment]
Interesting that the "unchecked" state does not propagate.
Just for the sake of sanity check, if you select it, save settings and then unselect and save settings again - will the setting work for you?

**Comment by zkiss** [comment]
Yes, I've tried that.

**Comment by AlexejK** [comment]
There is an issue in the default settings, however it should function properly as soon as the settings have been saved. #266 should cover the proper default values.

**Comment by zkiss** [comment]
Actually, the tick-save-untick-save trick solves it. When I tried it, I thought that this setting is global and not a per project setting.

**Comment by AlexejK** [comment]
Yes, we will look into making things "global" but defaults should've been "off" to begin with.
This is a bug that should be fixed in #266.

You can also create project default settings as a workaround, but that is only applied to new settings. Sorry for this issue, we can see if we can push out a patch for this soon. Unfortunately it requires some action from @mplushnikov.
