### ISSUE TITLE
'Lombok Dependency is possible outdated' message even when 'Enable lombok version warning' is unchecked.

### ISSUE THREAD

**Issue by corneil** [mplushnikov/lombok-intellij-plugin#268]
I have checked to make sure it happens every time I open a project with Lombok plugin enabled.
The project is based on Spring Boot and I am not going to mess with their curated list of dependencies.

I would also suggest that you add two links to the warning dialog:
* Disable Lombok plugin
* Disable lombok version check

**Comment by AlexejK** [comment]
There is a bug with those settings and its already fixed in main branch. Fix was part of #266 
To see the outcomes of discussions please look at #263.

Disable suggestion is very similar to point 3 in my summary that is not a blocker as default setting should default to "disabled" even though, due to a bug, checkboxes indicated disabled, while they weren't.

To workaround for your project until the bugfix is released - please select "enable version check", save settings and then disable again. This will work around the issue for the time being.
