### ISSUE TITLE
Not working for IDEA 2016.1.3 nor 2016.2.1

### ISSUE THREAD

**Issue by KingFaris10** [mplushnikov/lombok-intellij-plugin#277]
I tried adding Lombok to IDEA 2016.1.3 and it says in red 'Plugin is incompatible with current IntelliJ IDEA platform.' I updated my IntelliJ to 2016.2.1 and it still says the same error.

**Comment by Janmm14** [comment]
Which version of the plugin are you using?

**Comment by KingFaris10** [comment]
0.13.14

**Comment by KingFaris10** [comment]
@Janmm14 I'm using 0.13.14

**Comment by AlexejK** [comment]
Instead of manually downloading -  follow the guide in Readme to install it directly via IDEA. 

Reason why you are getting this issue is that The version you picked is for IntelliJ 14. For 2016.+ you must use of versions of plugin ending with ". 16"

Also,  if you upgrade to IDEA 2016.2, some of the features of this plugin will be enhanced.

**Comment by KingFaris10** [comment]
Oh right, thanks.
