### ISSUE TITLE
Feature Request: Add support for @FieldNameConstants

### ISSUE THREAD

**Issue by jknight** [mplushnikov/lombok-intellij-plugin#475]
It would be great to have support for the new experimental feature [FieldNameConstansts](https://projectlombok.org/features/experimental/FieldNameConstants)

**Comment by soberich** [comment]
This will be promoted very soon. @mplushnikov  would be great if we may already start to evaluate this as it is available in `edge`. Due to specifics of our current project, for example, this feature is highly wanted, the blocker now is that plugin does not support this to quickly start working with the new lombok feature in IDE.

**Comment by eximius313** [comment]
+1, this is really important feature

**Comment by soberich** [comment]
@mplushnikov Common guys. It's in 1.18 delivered. Maybe a little guidence as I commented above. 
Thanks.

**Comment by eximius313** [comment]
When do you plan to release `0.19`?

**Comment by mplushnikov** [comment]
@eximius313 End of this week probably

**Comment by mplushnikov** [comment]
This should be fixed in the next release 0.19
