### ISSUE TITLE
@FieldNameConstants incompatible with Intelij Idea 2019.1 

### ISSUE THREAD

**Issue by sahkaa** [mplushnikov/lombok-intellij-plugin#619]
### Short description
Intelij Idea shows red for const usage.
![image](https://user-images.githubusercontent.com/22525075/55952202-b2a12880-5c61-11e9-93f8-f1d992475069.png)
But everything else works properly. I'm able to run the tests and compile from IDE.

**Comment by kennyliao1982** [comment]
@sahkaa 
I was facing the same problem as yours.
After checking again the lombok plugin source and document, now I see what's happening.

The new version of intellij lombok plugin uses lombok v1.18.6, which the underlying implementation of @FieldNameConstants was just redesigned and the IDE just can't recognize the "FLELD_" constants anymore.

please refer to the document here
https://projectlombok.org/features/experimental/FieldNameConstants.

It still runs well when compiling and testing  because you set up the older version of lombok as the project dependency.


Hopefully there will be a fix soon!

**Comment by nister** [comment]
The same problem. I tried different version of plugin (IDEA 2019.1, 2018.3.x) and this is last one that works correctly:
https://plugins.jetbrains.com/files/6317/53293/lombok-plugin-0.23-2018.3.zip?updateId=53293&pluginId=6317&family=intellij

All newer version has such problem.
I hope this problem will be fixed soon!

**Comment by mplushnikov** [comment]
You can just update your lombok dependency to a new one. Current version of plugin only supports new style of @FieldNameConstants annotation
