### ISSUE TITLE
Incremental compilation is broken

### ISSUE THREAD

**Issue by rmannibucau** [mplushnikov/lombok-intellij-plugin#646]
### Short description

Seems lombok breaks incremental compilation.

Example: my project uses JPA and build time enhancement (so after compilation, a mvn plugin is executed to enhance JPA entities). If I modify a class which is not an entity or an upstream dependency of an entity I expect idea to not recompile the entity - and therefore not require me to rerun the enhancement plugin manually. However this is not the case when lombok plugin is setup. This is likely a bug in lombok annotation processor but if the plugin can workaround it or at least identify there is a plugin to run it would be very nice.

### Expected behavior

Incremental compilation shouldn't be broken.

### Version information

 * **IDEA Version:** 2019.1.3
 * **JDK Version:** 8
 * **OS Type & Version:** Ubuntu 19.04
 * **Lombok Plugin Version:** 0.25-EAP
 * **Lombok Dependency Version:** 1.18.4

### Steps to reproduce
_What steps do we need to take to reproduce this issue?_

 1. Clone https://github.com/rmannibucau/rblog
 2. Run "process-classes" once (through mvn)
 3. Modify a JAX-RS endpoint and run tests, it will likely run on entities not enhanced and fail

### Sample project
Please provide a sample project that exhibits the problem.
You should also include `.idea` folder so we can inspect the settings.

 - [] Sample project provided
 - [ ] I am able to reproduce this error on the sample project by following the steps described above

**Comment by mplushnikov** [comment]
Compiler dosn't normally know what will be changed by lombok annotation processor, so it have to recompile all classes again by default.

But I think this should be going better with IntelliJ 2020.3 EAP because of changes made here: https://youtrack.jetbrains.com/issue/IDEA-250718

Try it, maybe you will see any difference, be sure to use lastest lombok version, like 1.18.16, because old one will not work.
