### ISSUE TITLE
Incompatible with Intellij Chinese ​(Simplified)​ Language Pack EAP

### ISSUE THREAD

**Issue by fevenor** [mplushnikov/lombok-intellij-plugin#841]
### Short description
Enable both Lombook Plugin and Chinese ​(Simplified)​ Language Plugin, IDEA cannot resolve symbol on"@RequiredArgsConstructor(onConstructor = @__(@Autowired))".

![image](https://user-images.githubusercontent.com/3345319/88743424-42305a80-d177-11ea-9696-cdfc191a805f.png)

### Expected behavior
IDEA  can resolve symbol.

### Version information
* **IDEA Version:** 2020.2
* **Lombok Plugin Version:** 0.30-EAP
* **Chinese ​(Simplified)​ Language Pack EAP:** 202.400

**Comment by mplushnikov** [comment]
Similar issue #832, possible duplicate

**Comment by KENNYSOFT** [comment]
### Short description

Also occurs with Korean Language Pack EAP.

![image](https://user-images.githubusercontent.com/6624567/105528111-e7dc1500-5d27-11eb-8e17-2b1a916ecb24.png)

https://github.com/mplushnikov/lombok-intellij-plugin/blob/releasebuild_0.34-2020.1/src/main/java/de/plushnikov/intellij/plugin/handler/OnXAnnotationHandler.java#L15-L16

According to the code, I understand that the plugin makes the IDE just ignore the error message if some conditions are met. But since Language Pack is applied, the error message comes in a different format, so it cannot match the regex.

### Version information
* **IDEA Version:** 2020.3.1
* **Lombok Plugin Version:** Bundled 203.6682.168
* **Chinese ​(Simplified)​ Language Pack EAP:** 203.556
