### ISSUE TITLE
IntelliJ + Lombok + Eclipse Compiler?

### ISSUE THREAD

**Issue by wibbo** [mplushnikov/lombok-intellij-plugin#89]
Hello

Is it possible to use the lombok-intellij-plugin togehter with the eclipse compiler in IntelliJ?

I've search aground but haven't found any information.

Thanks for your great work!

**Comment by mikesmiffy128** [comment]
This plugin only changes how IntelliJ interprets the code. The compiler logic is still handled by Lombok itself, so there should be no problem there at all :+1:

**Comment by thaibui** [comment]
I am having the same problem. Intellij + Eclipse Compiler + Lombok doesn't compile because of unable to understand generated getter methods. Do you have any idea why?

You can make a simple test by using the @Data annotation, use the object's setter in the code and compile the code. The Eclipse compiler will say that "getSomething()" not found, while the regular "javac" compiler works just fine.

Thanks!

**Comment by dsebban** [comment]
I have the same issue , eclipse compiler in IntelliJ  is used by TDDers to speed junit test , the Lombok plugin does not work with it

**Comment by jmisur** [comment]
Working solution: http://stackoverflow.com/questions/24006937/lombok-annotations-do-not-compile-under-intellij-idea/30125507#30125507

**Comment by seanf** [comment]
Thanks for the pointer, @jmisur !

**Comment by mplushnikov** [comment]
Thanks @jmisur! Added this steps to the main page.

**Comment by stefaneicher** [comment]
I am having also the same problem as described above. are there any news?

**Comment by BullshitPingu** [comment]
Hi there! 

I'd like to know if there are any plans on this? I wasted a lot of time in finding on how to solve it, because who looks up the README page in the first place when they just want to install the lombok plugin via IntelliJ. As a user I'd wish it would work right out of the box.

Is it possible to either fix it (I guess that is possible?), or include a warning in the lombok plugin settings page within IntelliJ (Like the ones already included behind `Enable Lombok plugin for this project`)?

Thanks in advance!

**Comment by JonSnow592622272** [comment]
> I am having the same problem. Intellij + Eclipse Compiler + Lombok doesn't compile because of unable to understand generated getter methods. Do you have any idea why?
> 
> You can make a simple test by using the @DaTa annotation, use the object's setter in the code and compile the code. The Eclipse compiler will say that "getSomething()" not found, while the regular "javac" compiler works just fine.
> 
> Thanks!

I have the same problem.！！！！！！！！！！！！
try it:
