### ISSUE TITLE
Plugin is displayed as Not Compatible with IntelliJ 2020.2

### ISSUE THREAD

**Issue by saborse** [mplushnikov/lombok-intellij-plugin#916]
After upgrading the intellij version to 2020.2 (Ultimate edition), lombok plugin stopped working

**Comment by stroym** [comment]
That's because it's not compatible - and the developer knows. (They've known since mid last week.)
Please check for closed issues (of which there are multiple) or read the project description.

There should be a fix in the 2020.2.1 release as well as a fixed up plugin version for that release, but there seems to be some trouble in getting Idea to download it from the plugin center. Some people have reported you have to uninstall and then install the plugin to get the proper version, but I've personally had no such luck, so I'm back on 2020.1 until this gets sorted out.

**Comment by hakuseki** [comment]
Uninstalling and reinstalling worked perfectly fine. Thx for the tip @stroym

**Comment by saborse** [comment]
Yes, reinstalling worked, thnx.
