### ISSUE TITLE
Support IntelliJ 2020.3

### ISSUE THREAD

**Issue by brianvallred** [mplushnikov/lombok-intellij-plugin#989]
### Short description
No Lombok plugin available for IntelliJ IDEA 2020.3

### Expected behavior
It should be available

### Version information

 * **IDEA Version:** 2020.3
 * **JDK Version:** 1.8
 * **OS Type & Version:** Windows and Mac
 * **Lombok Plugin Version:** <none>
 * **Lombok Dependency Version:** 

### Steps to reproduce
Just try updating IntelliJ IDEA from 2020.2 to 2020.3

### Sample project
<none>

**Comment by lealceldeiro** [comment]
Same on Linux!

**Comment by lealceldeiro** [comment]
Lombok is now bundled. See #987

**Comment by Sunyb01** [comment]
So, do I need to uninstall my community version when I upgrade to 2020.3?

**Comment by ruurd** [comment]
Did you already try to update? If the update dialog shows then you have an incompatible version of lombok. As soon as you update problems are gone because your lombok plugin is also updated.

**Comment by mirabilos** [comment]
I don’t quite get this. I have to remove the plugin first, then update the IDE? Because the IDE update mentions Lombok as incompatible plugin… (this also forces me to update all installations I have in lockstep because I have the settings sync active…)

**Comment by ruurd** [comment]
The point in time that you see the update dialog you still are in 2020.2.x with the OLD plugin so the message is indeed factual. The Lombok plugin is at that time the old one which is incompatible with 2020.3 - however when you install 2020.3 the bundled Lombok will also be installed. Right?

**Comment by novicedev7291** [comment]
@ruurd I did not find Lombok plugin bundled with intelij 2020.3, I have read everywhere people saying that it is bundled but it seems it is not.

**Comment by getaceres** [comment]
It seems to NOT be bundled with the community edition although the What's New doesn't specify that it's an Ultimate only feature. 
I've upgraded IntelliJ with the plugin installed and suddenly I couldn't run anything inside IntelliJ because it failed recognizing the generated Builder classes. It doesn't fail in the editor but it fails to compile the project as soon as I try to run a unit test. If I uninstall the plugin then IntelliJ complains about all getters/setters, etc so it seems it's not part of the Community Edition.
So I'm confused here. Is it part of IntelliJ in the same sense that Maven is part of it and you don't have to install anything? Or is it that the plugin has been taken over by JetBrains and they will update it with every new release of IntelliJ? Do I have to wait for support for IntelliJ 2020.3 or is it an Ultimate feature only?

**Comment by mplushnikov** [comment]
Sorry guys, I have to confirm, it was forgotten to add it properly into the last community build. 
See bug on Jetbrains Yourtrack: **https://youtrack.jetbrains.com/issue/IDEA-257311**

The Ultimate 2020.3 version contains lombok plugin as expected per default.

lombok plugin should be included in **both** IntelliJ distribution (Ultimate and Community) starting with 2020.3 release. Something get wrong, we are working to fix it.

**Comment by mplushnikov** [comment]
Fix is now planned for IntelliJ Community release 2020.3.1

**Comment by smilep** [comment]
Now that 2020.4 version is out, does it contains the fix?

**Comment by mplushnikov** [comment]
2020.3.1 Community is released and contains lombok plugin by default now
