### ISSUE TITLE
How to debug the lombok-intellij-pligins ?

### ISSUE THREAD

**Issue by Zengzehao** [mplushnikov/lombok-intellij-plugin#994]
### Short description
How to debug the lombok-intellij-pligins ? 
I am a freshman and want to know how to add  a new feature to  lombok-intellij-pligins .
There is any methods to debug the lombok-intellij-pligins?

**Comment by NekoCaffeine** [comment]
The first thing you need to know about `Gradle`.

After cloning the project, open it with IDEA, open the `Gradle` tab, and click on the Sync button (the two encircling arrows).
This process will download the Intellij source code for you, which will take some time, so please try again when the network fluctuation fails.

Next, in the `Gradle` tab, expand the project `Tasks > intellij`, `right-click` on `runIde` and select `Debug` to start it.
The rest is no different than debugging a normal Java application.

But please note: You `MUST` get the compiler to support your new feature as well, otherwise you will see compiler errors.

For the compiler (javac or ecj), see: https://github.com/rzwitserloot/lombok
If you need help, please contact me via QQ( 931920447 ).
